# Generated by Django 4.2.10 on 2024-10-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0004_delete_serveroperations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="expire_date",
            field=models.DateTimeField(null=True),
        ),
    ]
