# Generated by Django 4.2.10 on 2024-10-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0005_alter_schedule_expire_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="problem_code",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="problem",
            name="status",
            field=models.CharField(
                choices=[
                    ("AC", "Accepted"),
                    ("NA", "Not Attempted"),
                    ("SP", "Sample Problem"),
                ],
                default="NA",
                max_length=2,
            ),
        ),
    ]
