# Generated by Django 4.2.10 on 2025-01-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0003_serveroperations"),
    ]

    operations = [
        migrations.AddField(
            model_name="serveroperations",
            name="message",
            field=models.TextField(null=True),
        ),
    ]
