# Generated by Django 4.2.10 on 2025-01-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0004_serveroperations_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_leetcode_username_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="leetcode_username",
            field=models.CharField(default="user-name", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="server_region",
            field=models.CharField(
                choices=[("CN", "China Mainland"), ("US", "United States")],
                default="US",
                max_length=2,
            ),
        ),
    ]
