# Generated by Django 4.2.10 on 2024-10-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0002_serveroperations_schedule_start_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule", old_name="server", new_name="server_region",
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_name_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schedule",
            name="weekly_goal",
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name="problem",
            name="status",
            field=models.CharField(
                choices=[("AC", "Accepted"), ("NA", "Not Attempted")],
                default="NA",
                max_length=2,
            ),
        ),
    ]
