# Generated by Django 4.2.10 on 2025-01-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0006_problem_problem_code_alter_problem_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem", old_name="problem_name", new_name="problem_title",
        ),
        migrations.RemoveField(model_name="schedule", name="is_name_public",),
        migrations.RemoveField(model_name="schedule", name="last_update",),
        migrations.RemoveField(model_name="schedule", name="leetcode_username",),
        migrations.RemoveField(model_name="schedule", name="server_region",),
        migrations.RemoveField(model_name="schedule", name="weekly_goal",),
        migrations.AddField(
            model_name="problem",
            name="problem_slug",
            field=models.CharField(default="default-slug", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="problem",
            name="proof_url",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="schedule", name="goals", field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="schedule",
            name="schedule_type",
            field=models.CharField(
                choices=[("FREE", "Free"), ("NORMAL", "Normal"), ("ROOT", "Root")],
                default="FREE",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="done_date",
            field=models.DateTimeField(null=True),
        ),
    ]
