# Generated by Django 4.2.10 on 2025-01-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0007_rename_problem_name_problem_problem_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="sheet_row",
            field=models.IntegerField(null=True),
        ),
    ]
