# Generated by Django 4.2.10 on 2024-10-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0002_remove_member_motto"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerOperations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_name",
                    models.CharField(
                        choices=[
                            ("UPDATE_MEMBER", "Update Member"),
                            ("UPDATE_PROBLEM", "Update Problem"),
                            ("UPDATE_BENCHMARK", "Update Benchmark"),
                        ],
                        max_length=256,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
